<a href="https://colab.research.google.com/github/bmraffa/Linear-Algebra-1/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import scipy.linalg as la

In [ ]:
%matplotlib inline

In [ ]:
def mat_desc(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
R = np.array ([
    [3,-9,4],
    [0,5,2],
    [-2,11,8]
])
mat_desc(R)

Matrix:
[[ 3 -9  4]
 [ 0  5  2]
 [-2 11  8]]

Shape:	(3, 3)
Rank:	2



In [ ]:
def mat_desc(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [5,10,15],
    [2,4,6],
    [3,6,9]
])

non_square_mat = np.array([
    [5,10,15],
    [2,4,6]
])
mat_desc(square_mat)
mat_desc(non_square_mat)

Matrix:
[[ 5 10 15]
 [ 2  4  6]
 [ 3  6  9]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[ 5 10 15]
 [ 2  4  6]]

Shape:	(2, 3)
Rank:	2
Is Square: False



In [ ]:
def mat_desc(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([
           [0,0,0],
           [0,0,0]
])
mat_desc(null_mat)

Matrix:
[[0 0 0]
 [0 0 0]]

Shape:	(2, 3)
Rank:	2
Is Square: False



In [ ]:
import numpy as np

In [ ]:
zero_mat_row = np.zeros((3,3))
zero_mat_sqr = np.zeros((3,3))
zero_mat_rct = np.zeros((3,3))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,3))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
A = np.array([
    [1,2,6,7],
    [2,3,8,9],
    [4,1,6,5]
])
B = np.array([
    [2,2,6,6],
    [0,0,1,1],
    [1,1,3,3]
])
print(A+B)

[[ 3  4 12 13]
 [ 2  3  9 10]
 [ 5  2  9  8]]


In [ ]:
print(4+A)

[[ 5  6 10 11]
 [ 6  7 12 13]
 [ 8  5 10  9]]


In [ ]:
B-A

array([[ 1,  0,  0, -1],
       [-2, -3, -7, -8],
       [-3,  0, -3, -2]])

In [ ]:
5-B == 5*np.ones(B.shape)-B

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A*B
np.multiply(A,B)

array([[ 2,  4, 36, 42],
       [ 0,  0,  8,  9],
       [ 4,  1, 18, 15]])

In [ ]:
4*A

array([[ 4,  8, 24, 28],
       [ 8, 12, 32, 36],
       [16,  4, 24, 20]])

In [ ]:
A/B
np.divide(A,B)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[0.5       , 1.        , 1.        , 1.16666667],
       [       inf,        inf, 8.        , 9.        ],
       [4.        , 1.        , 2.        , 1.66666667]])