<a href="https://colab.research.google.com/github/bmraffa/Linear-Algebra-1/blob/main/Assignment6_Besanes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Activity 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than  (3,3) . In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [17]:
A = np.array([
    [-1,3,0,13],
    [2,4,-5,7],
    [5,3,10,1],
    [1,5,0,9]
])
B = np.array([
    [-9,11,21,2],
    [1,6,-2,8],
    [9,18,-9,0],
    [2,6,1,0]
])
C = np.array([
    [1,0,0,2],
    [4,1,9,8],
    [17,3,1,-4],
    [3,7,2,1]
])

In [18]:
print( A.shape)
print( B.shape)
print( C.shape)


(4, 4)
(4, 4)
(4, 4)


#####First Property: $A \cdot B \neq B \cdot A$

In [21]:
np.dot(A,B)

array([[ 38,  85, -14,  22],
       [-45,  -2,  86,  36],
       [ 50, 259,  10,  34],
       [ 14,  95,  20,  42]])

In [22]:
np.dot(B,A)

array([[ 138,   90,  155,   -1],
       [   9,   61,  -50,  125],
       [ -18,   72, -180,  234],
       [  15,   33,  -20,   69]])

In [23]:
np.array_equal(A,B)

False

In [24]:
np.array_equiv(A,B)

False

#####Second Property: $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [27]:
D = A @ (B @ C)
D

array([[ 206,  197,  795,  834],
       [1517,  508,  140, -414],
       [1358,  527, 2409, 2166],
       [ 860,  449,  959,  750]])

In [29]:
E = (A @ B) @ C
E

array([[ 206,  197,  795,  834],
       [1517,  508,  140, -414],
       [1358,  527, 2409, 2166],
       [ 860,  449,  959,  750]])

In [31]:
np.array_equal(D,E)

True

In [32]:
np.array_equiv(D,E)

True

#####Third Property: $A\cdot(B+C) = A\cdot B + A\cdot C$

In [33]:
F = A @ (B+C)
F

array([[ 88, 179,  39,  57],
       [-91,  36, 131,  99],
       [240, 299,  49,  29],
       [ 62, 163,  83,  93]])

In [34]:
G = (A @ B) + (A @ C)
G

array([[ 88, 179,  39,  57],
       [-91,  36, 131,  99],
       [240, 299,  49,  29],
       [ 62, 163,  83,  93]])

In [35]:
np.array_equal(F,G)

True

In [36]:
np.array_equiv(F,G)

True

#####Fourth Property: $(B+C)\cdot A = B\cdot A + C\cdot A$

In [37]:
H = (B + C) @ A
H

array([[ 139,  103,  155,   30],
       [  60,  144,   35,  265],
       [ -28,  118, -185,  441],
       [  37,   81,  -35,  168]])

In [43]:
J = (B @ A) + (C @ A)
J

array([[ 139,  103,  155,   30],
       [  60,  144,   35,  265],
       [ -28,  118, -185,  441],
       [  37,   81,  -35,  168]])

In [44]:
np.array_equal(H,J)

True

In [45]:
np.array_equiv(H,J)

True

#####Fifth Property: $A\cdot I = A$

In [49]:
I = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])

In [50]:
np.dot(A,I)

array([[-1,  3,  0, 13],
       [ 2,  4, -5,  7],
       [ 5,  3, 10,  1],
       [ 1,  5,  0,  9]])

In [58]:
np.dot(B,I)

array([[-9, 11, 21,  2],
       [ 1,  6, -2,  8],
       [ 9, 18, -9,  0],
       [ 2,  6,  1,  0]])

In [59]:
np.dot(C,I)

array([[ 1,  0,  0,  2],
       [ 4,  1,  9,  8],
       [17,  3,  1, -4],
       [ 3,  7,  2,  1]])

In [51]:
np.array_equal(A,I)

False

In [60]:
np.array_equal(B,I)

False

In [61]:
np.array_equal(C,I)

False

In [52]:
np.array_equiv(A,I)

False

In [62]:
np.array_equiv(B,I)

False

In [64]:
np.array_equiv(C,I)

False

#####Sixth Property: $A\cdot \emptyset = \emptyset$ 

In [54]:
O = np.array([
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0]
])

In [55]:
np.dot(A,O)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [65]:
np.dot(B,O)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [66]:
np.dot(C,O)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [56]:
np.array_equal(A,O)

False

In [67]:
np.array_equal(B,O )

False

In [68]:
np.array_equal(C,O)

False

In [57]:
np.array_equiv(A,O)

False

In [69]:
np.array_equiv(B,O)

False

In [70]:
np.array_equiv(C,O)

False